version: "3.9"

services:
  web:
    build: .
    container_name: api_scania
    ports:
      - "8001:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - pg-docker_default

networks:
  pg-docker_default:
    external: true